export const regexIndukHurufMap = {
  ka: /[KkQq]/g,
  ga: /[g]/g,
  nga: /[G]/g,
  pa: /[PpFfvV]/g,
  ba: /[Bb]/g,
  ma: /[Mm]/g,
  ta: /[Tt]/g,
  da: /[Dd]/g,
  na: /[n]/g,
  ca: /[Cc]/g,
  ja: /[JjZz]/g,
  nya: /[N]/g,
  ya: /[y]/g,
  a: /[a]/g,
  la: /[Ll]/g,
  ra: /[r]/g,
  sa: /[Ss]/g,
  wa: /[w]/g,
  ha: /[h]/g,
  kha: /[H]/g,
  gha: /[H]/g,
};

export const regexAnakHurufMap = {
  nengen: /a[\/]/g,
  ulan_i: /a[i]/g,
  ulan_e: /a[E]/g,
  bicek_e: /a[e]/g,
  bitan_o: /a[Oo]/g,
  bitan_u: /a[u]/g,
  tekelubang: /X/g,
  rejunjung: /R/g,
  datasan: /A/g,
  tekelungau: /W/g,
  tekelingai: /I/g,
  keleniah: /x/g,
};

export const regexPatterns = {
  ng: /(ng)[aiueoAIUEO]/g,
  ny: /(ny)[aiueoAIUEOkKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHh]/g,
  gh: /(gh|kh)[aiueoAIUEOkKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHh]/g,
  vocal: /^[iIuUeEoO]/,
  tandabaca: /[,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]/,
  ang: /[aiueoIUEO](ng)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  an: /[aiueoIUEO](n)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  ah: /[aiueoIUEO](h)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  ar: /[aiueoIUEO](r)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  ai: /[aiueoIUEO](i)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  au: /[aiueoIUEO](u)[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]]/g,
  xawal:
    /[aiueoIUEO][kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWH][kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWH][aiueoIUEO]/g,
  x: /(?![aeiouAEIOU](R|r|u|n|h|ng|gh|kh|i))[aiueoIUEO]([kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWHnhriu])[,!@.*+?$^/\\;:'"[\]{}()%#^+=_-]?$/g,
  xng: /[aiueoIUEO]ng$/g,
  anx: /[aiueoIUEO]n/g,
  ahx: /[aiueoIUEO]h/g,
  arx: /[aiueoIUEO]r\b/g,
  aix: /[aiueoIUEO]i/g,
  aux: /[aiueoIUEO]u/g,
  a: /[kKQqgpPfFvVbBmMtTdDcCjJzZyYlLsSwWGHhnr][a]/g,
  awal: /\b[iIuUeEoOXAR]/g,
  digraph: /(?<!n|g|y|h)(?!ng|ny|gh|kh)[b-df-hj-np-tv-z]{2}/g,
};
